return {
  unpack(require "plugins.rust"),
  unpack(require "plugins.lsp"),
  unpack(require "plugins.dap"),
  unpack(require "plugins.ui"),
  unpack(require "plugins.neominimap"),
  unpack(require "plugins.illuminate"),
  unpack(require "plugins.ufo"),
  unpack(require "plugins.whichkey"),
  unpack(require "plugins.schemastore"),
  unpack(require "plugins.tree"),
  unpack(require "plugins.treesitter"),
  unpack(require "plugins.mason"),
  unpack(require "plugins.gitsigns"),
  unpack(require "plugins.theme"),
}
